name: Cognizant Notes Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
  #    - name: Build Android APP
  #      run: eas build --platform android --profile production 
  #    - name: Submit Android App
  #      run: eas submit --platform android --latest --profile production --non-interactive
      - name: Build Local Android Package
        run: eas build --platform android --profile production --local --output ${{ github.workspace }}/app-release.aab
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.aab 
      - name: Upload .aab to Internal Track
        id: upload_internal
        uses: KevinRohn/github-action-upload-play-store@v1.0.0
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: "com.rodeliosr.cognizantnotes"
          aab_file_path: "${{ github.workspace }}/app-release.aab"
          track: "internal"
          release_status: "draft"
     
